# .github/workflows/firebase.yml
permissions:
  contents: write

name: Build and Deploy

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare public folder
        run: mkdir -p public

      - name: Inject secret
        run: |
          echo "window['_f'] = '${{ secrets.FIREBASE_API_KEY }}';" > public/guitartracks.js
          echo "Injected config:"
          cat public/guitartracks.js
          
      - name: List public folder
        run: ls -l public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

