# .github/workflows/firebase.yml
permissions:
  contents: write

name: Build and Deploy

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare public folder
        run: mkdir -p public

      - name: Inject API key
        run: |
          echo "window.FIREBASE_API_KEY = atob('${{ secrets.FIREBASE_API_KEY_BASE64 }}');" > public/z.js

      - name: Debug check
        run: |
          echo "--- Contents of ./public ---"
          find public
          echo "--- z.js ---"
          cat public/z.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
